#! /bin/sh

# Pick new (big) external monitor to work on (NOT laptop screen)
xrandr --output eDP1 --off
bspc config remove_disabled_monitors true
xrandr --output HDMI1 --primary --mode 1920x1080 --rotate normal

/usr/local/bin/sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc rule -a Gimp desktop='^7' state=floating follow=on
#bspc rule -a Firefox state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a flameshot state=floating
